### PR TITLE
Add erase option to remove all items from a board

### PR DESCRIPTION
**Pull request by klao**

### CODE REVIEW

**Comment by mrichar1** [comment]
Hi, thanks for this PR!

Got a couple of thoughts on this...

Firstly, this is a potentially dangerous option, since it wipes the entire board. I'd perhaps prefer for it to be hard to use by accident.

So it probably shouldn't have a short option (i.e. no `-e`). It should probably also be called something very different from delete (I can imagine someone typing `clipster --erase` when they meant `clipster --delete`). Perhaps it should be named something like `--erase-entire-board` to make it clear that is what's happening?

Secondly, I'm not sure what to do about `sync_selections` - I'm not sure if erasing one board should also wipe the other if this option is set - any thoughts?

Either way this probably needs a test added, and an update to the `README` to highlight this new command option and update the protocol docs to add the `ERASE` option.

Let me know what you think about these suggestions, and if you're happy to make them, or would like some help.

**Comment by klao** [comment]
These sound reasonable, I'll do them tomorrow!

I was also thinking about `sync_selections`, I think it should keep the boards in sync. But, there are already some inconsistency: deleting from the UI keeps the board in sync, but from the command like doesn't... So, I was thinking of doing it in a separate PR, together with cleaning up that too.

**Comment by klao** [comment]
Thanks!

I was still working on the test though! :)  Will send you a separate PR if you want.

**Comment by mrichar1** [comment]
Oops - yes please! :blush:

**Pull request merged**
