### PR TITLE
Clear selection if the current item is deleted

### PR DESCRIPTION
**Pull request by klao**
This makes the code that selects the previous item from history to
properly trigger.

Also, don't try to set the selection if the history is empty.

### CODE REVIEW

**Comment by mrichar1** [comment]
Thanks for this PR.

Firstly, I should start by saying I've just noticed a regression in the code when I refactored the client action, which meant that `delete` and `search` options weren't working properly.  So this might affect the intent/effect of this PR.

Secondly, I have to admit to not being clear on what the intent of the first part is.  If data is an empty string, it is falsey, so not sure why you need to set it to None. I'm also not sure what the advantage is to calling `set_text` with an empty string (length 0) *and* calling `clear()` over just using `""` and using `-1` to let Gtk sort it out internally.

The second part (testing the list) is definitely a bug though, so happy to accept that part.

**Comment by mrichar1** [comment]
(Also there's a minor issue that the extra blank line is causing test failure due to pep8).

**Comment by klao** [comment]
The `None` seems cleaner to me, an obvious indication that we are removing the selection. But, I'm totally fine with the empty string too.

I don't know why I used `0` instead of `-1`. I think I was just debugging and trying different things and forgot it like that. :)

The `clear()` after the `set_text("", -1)` is important, though. It doesn't work without it for me. Neither the `clear()` nor the `set_text("", -1)` seem to be enough on their own. Only if both of them are used in this order, only then deleting the most recent item works reliably for me.

I am happy to investigate what's different on my machine if you have some ideas and things to try...

**Comment by mrichar1** [comment]
OK, I can sort of replicate the need for `set_text` and `clear` in some cases, if I select text in an app, then call `clipster -r` in some cases the app seems to re-fill the clipboard with either the last or a previous value. I can't always reproduce this, but having now seen it I'm happy to accept the clear addition as well (though personally I'd prefer to keep `data` as `''` rather than `None`). 

If you can patch that and the PEP8 issue I'm happy to accept this PR (I've also found some more similar `IndexError` exceptions I need to fix up as well, now I'm looking for them - thanks!

**Comment by klao** [comment]
Fixed. It's actually got simpler this way. :)

**Comment by mrichar1** [comment]
Looks good! Many thanks!

**Comment by klao** [comment]
Thank you too for incredibly responsive reviews!

**Comment by mrichar1** [comment]
Mostly luck that I was just thinking of checking some other things in the code when your PRs arrived!

Now released as `1.2.2` with another small fix (spotted thanks to you fixing a similar one).

**Pull request merged**
